name: Build artifacts

on:
  push:
    branches: ["next"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS
          - os: macos-latest
            target: aarch64-apple-darwin
            profile: debug
          - os: macos-latest
            target: aarch64-apple-darwin
            profile: release
          - os: macos-latest
            target: x86_64-apple-darwin
            profile: debug
          - os: macos-latest
            target: x86_64-apple-darwin
            profile: release

          # Linux
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            profile: debug
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            profile: release

          # Windows
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            profile: debug
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            profile: release

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.os == 'macos-latest' && matrix.target || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}-${{ matrix.profile }}

      - run: cargo build --target ${{ matrix.target }} ${{ matrix.profile == 'release' && '--release' || '' }}

      - uses: actions/upload-artifact@v4
        name: Upload bundles
        with:
          name: wavebreaker-${{ matrix.target }}-${{ matrix.profile }}
          path: target/${{ matrix.target }}/${{ matrix.profile }}/wavebreaker_installer*
